=== chastis/UniversityStuff/FifthSemester/Programming/Lab2_deprecated/Candy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:annotation>
        <xsd:documentation xml:lang="en"> Candy schema. 
        </xsd:documentation> 
    </xsd:annotation>
    
    <xsd:element name="Candies" type="Candies"/>
    
    <xsd:complexType name="Candies">
        <xsd:sequence> 
            <xsd:element name="Candy" type="CandyType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="CandyType">
        <xsd:sequence>
            <xsd:element name="Energy" type="xsd:nonNegativeInteger"/>
            <xsd:element name="Type">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="Caramel"/>
                        <xsd:enumeration value="Chocolate"/>
                        <xsd:enumeration value="Iris"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="Ingredients" type="IngredientsType"/>
            <xsd:element name="Value" type="ValueType"/>
            <xsd:element name="Production" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="attributeNameType"/>
        <xsd:attribute name="filled" type="xsd:boolean" use="optional"/>
    </xsd:complexType>
    
    
    
    <xsd:simpleType name="attributeNameType">
        <xsd:restriction base="xsd:string"> 
            <xsd:pattern value="[A-Za-z]+"/>
        </xsd:restriction> 
    </xsd:simpleType>
    
    <xsd:complexType name="IngredientsType">
        <xsd:sequence> 
            <xsd:element name="Ingredient" type="IngredientType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>       
    </xsd:complexType> 
    
    <xsd:complexType name="IngredientType">
        <xsd:sequence> 
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element name="Count" type="xsd:nonNegativeInteger"/>
        </xsd:sequence>       
    </xsd:complexType>
    
    <xsd:complexType name="ValueType"> 
        <xsd:sequence> 
            <xsd:element name="Proteins" type="xsd:nonNegativeInteger"/>
            <xsd:element name="Fats" type="xsd:nonNegativeInteger"/>
            <xsd:element name="Carbohydrates" type="xsd:nonNegativeInteger"/>
        </xsd:sequence> 
    </xsd:complexType> 
    
</xsd:schema>

=== chastis/UniversityStuff/FifthSemester/Programming/Lab2_deprecated/Candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Candy.xsl"?>

<Candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Candy.xsd">
    <Candy name="Candy1">
        <Energy>256</Energy>
        <Type>Iris</Type>
        <Ingredients>
            <Ingredient> 
                <Name>Water</Name>
                <Count>256</Count>
            </Ingredient>
            <Ingredient> 
                <Name>Sugar</Name>
                <Count>3</Count>
            </Ingredient>
            <Ingredient> 
                <Name>Fructose</Name>
                <Count>2</Count>
            </Ingredient>
            <Ingredient>
                <Name>Vanillin</Name>
                <Count>2</Count>
            </Ingredient>
        </Ingredients>
        <Value>
            <Proteins>3</Proteins>
            <Fats>2</Fats>
            <Carbohydrates>4</Carbohydrates>
        </Value>
        <Production>Roshen</Production>
    </Candy>
    
    <Candy name="Vyshnya">
        <Energy>512</Energy>
        <Type>Chocolate</Type>
        <Ingredients>
            <Ingredient> 
                <Name>Water</Name>
                <Count>18</Count>
            </Ingredient>
            <Ingredient> 
                <Name>Sugar</Name>
                <Count>1</Count>
            </Ingredient>
            <Ingredient> 
                <Name>Fructose</Name>
                <Count>2</Count>
            </Ingredient>
            <Ingredient>
                <Name>Vanillin</Name>
                <Count>3</Count>
            </Ingredient>
        </Ingredients>
        <Value>
            <Proteins>8</Proteins>
            <Fats>7</Fats>
            <Carbohydrates>6</Carbohydrates>
        </Value>
        <Production>Roshen</Production>
    </Candy>
</Candies>
